/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveList: typeof import('./src/components/ArchiveList.vue')['default']
    ArchiveMemoryPanel: typeof import('./src/components/ArchiveMemoryPanel.vue')['default']
    BubbleMenu: typeof import('./src/components/BubbleMenu.vue')['default']
    ChatComposer: typeof import('./src/components/ChatComposer.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    LogDialog: typeof import('./src/components/LogDialog.vue')['default']
    ModelSelect: typeof import('./src/components/ModelSelect.vue')['default']
    PillNav: typeof import('./src/components/PillNav.vue')['default']
    QuickOptions: typeof import('./src/components/QuickOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonAvatar: typeof import('./src/components/ui/SkeletonAvatar.vue')['default']
    SkeletonBlock: typeof import('./src/components/ui/SkeletonBlock.vue')['default']
    SkeletonText: typeof import('./src/components/ui/SkeletonText.vue')['default']
    StarterCard: typeof import('./src/components/StarterCard.vue')['default']
    StatusPanel: typeof import('./src/components/StatusPanel.vue')['default']
    StoryCard: typeof import('./src/components/StoryCard.vue')['default']
    StoryStatePanel: typeof import('./src/components/StoryStatePanel.vue')['default']
    StoryTimeline: typeof import('./src/components/StoryTimeline.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
